- hosts: consul_instances
  become: true
  become_user: root
  tasks:
    - name: Update apt cache
      apt: name=aptitude state=latest update_cache=yes force_apt_get=yes
      tags: [common]

- hosts: consul_instances
  become: true
  become_user: root
  roles:
    - {role: brianshumate.consul, tags: [consul]}
  vars:
    consul_version: '1.7.2'
    consul_datacenter: "{{ data_center }}"
    consul_acl_datacenter: "{{ data_center }}"
    consul_recursors: ['1.1.1.1', '1.0.0.1']
    consul_client_address: "0.0.0.0"

- hosts: docker_instances
  become: true
  become_user: root
  roles:
    - {role: geerlingguy.docker, tags: [docker]}
    - {role: brianshumate.nomad, tags: [docker, nomad]}
  vars:
    nomad_version: '0.10.3'
    nomad_datacenter: "{{ data_center }}"
    nomad_log_level: "DEBUG"
    nomad_servers: ["{{ hostvars['thinker.consul']['ansible_default_ipv4']['address'] }}:4647"]
    nomad_consul_address: "http://{{ hostvars['thinker.consul']['ansible_default_ipv4']['address'] }}:8500"
    nomad_bind_address: "0.0.0.0"
    nomad_use_consul: yes
    nomad_options: { 'driver.raw_exec.enable': '1' }
    nomad_bootstrap_expect: 1
    nomad_docker_enable: yes
    nomad_ports_http: 4646
    nomad_ports_rpc: 4647
    nomad_ports_serf: 4648
